#!/bin/sh
# Builds supabase/schema.sql: every migration, in order, in one file.
#
# Concatenation rather than a hand-written schema on purpose. The result is
# byte for byte the statements that already built the live database, in the same
# sequence, so it carries no risk that a rewritten schema would. A fresh project
# gets the whole thing from one paste.
#
# Run after adding a migration:  npm run db:schema
set -eu

cd "$(dirname "$0")/.."
out=supabase/schema.sql

{
  cat <<'HEADER'
-- ===========================================================================
-- FULL SCHEMA -- everything, in one file, for a fresh Supabase project.
--
-- This is every migration concatenated in order: byte for byte the same
-- statements, in the same sequence that built the live database. Paste it into
-- the SQL Editor of a new project and you have the whole thing.
--
-- Use this for a NEW project. For an existing one, run only the migrations it
-- has not seen yet. migrations/ holds those; migrations/archive/ holds the ones
-- already applied to the live database, kept for reference.
--
-- Every statement is idempotent, so running this against a database that
-- already has part of it is safe.
--
-- Generated by scripts/build-schema.sh -- do not hand-edit.
-- Regenerate with: npm run db:schema
-- ===========================================================================
HEADER

  # Sorted on the file's own name, so archive/0007 still comes before 0008.
  find supabase/migrations -name '*.sql' -type f |
    awk -F/ '{ print $NF "\t" $0 }' | sort | cut -f2- |
    while read -r file; do
      printf '\n\n-- #########################################################################\n'
      printf -- '-- ## %s\n' "$(basename "$file")"
      printf -- '-- #########################################################################\n\n'
      cat "$file"
    done
} > "$out"

printf 'wrote %s (%s lines from %s migrations)\n' \
  "$out" "$(wc -l < "$out" | tr -d ' ')" \
  "$(find supabase/migrations -name '*.sql' -type f | wc -l | tr -d ' ')"
